services:
  lint:
    image: buildkite/plugin-linter:v3.0.0
    command: ["--id", "OctopusDeploy/run-runbook"]
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester:v4.0.0
    volumes:
      - ".:/plugin:ro"
